### ISSUE TITLE
Is v3 published correctly?

### ISSUE THREAD

**Issue by Slessi** [myl7/remark-github-beta-blockquote-admonitions#10]
https://www.npmjs.com/package/remark-github-beta-blockquote-admonitions?activeTab=versions

Over here it says latest is `2.1.3` instead of `3.0.0`

Doesn't block me, can install v3 just fine, but shows as "outated" with `npm outdated`

**Comment by myl7** [comment]
2.1.3 is released after 3.0.0 since it needs backported later.
`npm publish` by default makes every version going through it as latest, so now 2.1.3 is marked as latest unexpectedly. My fault that did not foresee the situation.

I searched and have not found a way to change the latest tag on NPM (unlike GitHub release). One solution is to publish a new version again, which is a little wired to publish an empty, no-content version though. So I left it as is.

Do you think the `npm outdated` problem is problematic enough that we need the above solution?

**Comment by Slessi** [comment]
isnt it just

```
npm dist-tag add remark-github-beta-blockquote-admonitions@3.0.0 latest
```

**Comment by myl7** [comment]
Surprisingly simple... Thanks a lot. Now the latest tag has pointed to v3.0.0.
